import { Controller, Get, Post, UseGuards, Request } from '@nestjs/common';
import { AuthGuard } from '@nestjs/passport';
import { AuthService } from './auth/auth.service';

@Controller()
export class AppController {
    
  constructor(private readonly authService : AuthService) {}
  
  @Post('/login')           // Define the login method to issue the id card jwt token
  @UseGuards(AuthGuard('local'))            // Use the AuthGuard to protect the login route
  login(@Request() req): string {               // Use the AuthGuard to protect the login route
    // authentication completed
    return this.authService.generateToken(req.user);        // Return the token generated by the AuthService
  }
}
